abbrevs = {
            'Atlanta': ['atlanta', 'atl', 'hawks', 'atlantahawks'],
            'Brooklyn': ['brooklyn', 'bkn', 'nets', 'brooklynnets'],
            'Boston': ['boston', 'bos', 'celtics', 'bostonceltics'],
            'Charlotte': ['charlotte', 'cha', 'hornets', 'charlottehornets'],
            'Chicago': ['chicago', 'chi', 'bulls', 'chicagobulls'],
            'Cleveland': ['cleveland', 'cle', 'cavaliers', 'clevelandcavaliers', 'cavs'],
            'Dallas': ['dallas', 'dal', 'mavericks', 'dallasmavericks', 'mavs'],
            'Denver': ['denver', 'den', 'nuggets', 'denvernuggets'],
            'Detroit': ['detroit', 'det', 'pistons', 'detroitpistons'],
            'Golden State': ['goldenstate', 'gsw', 'warriors', 'goldenstatewarriors'],
            'Houston': ['houston', 'hou', 'rockets', 'houstonrockets'],
            'Indiana': ['indiana', 'ind', 'pacers', 'indianapacers'],
            'LA Clippers': ['laclippers', 'lac', 'clippers'],
            'LA Lakers': ['lalakers', 'lal', 'lakers'],
            'Memphis': ['memphis', 'mem', 'grizzlies', 'memphisgrizzlies'],
            'Miami': ['miami', 'mia', 'heat', 'miamiheat'],
            'Milwaukee': ['milwaukee', 'mil', 'bucks', 'milwaukeebucks'],
            'Minnesota': ['minnesota', 'min', 'timberwolves', 'minnesotatimberwolves'],
            'New Orleans': ['neworleans', 'nop', 'pelicans', 'neworleanspelicans'],
            'New York': ['newyork', 'nyk', 'knicks', 'newyorkknicks'],
            'Oklahoma City': ['oklahomacity', 'okc', 'thunder', 'oklahomacitythunder'],
            'Orlando': ['orlando', 'orl', 'magic', 'orlandomagic'],
            'Philadelphia': ['philadelphia', 'phi', '76ers', 'philadelphia76ers'],
            'Phoenix': ['phoenix', 'phx', 'suns', 'phoenixsuns'],
            'Portland': ['portland', 'por', 'trailblazers', 'portlandtrailblazers'],
            'Sacramento': ['sacramento', 'sac', 'kings', 'sacrementokings'],
            'San Antonio': ['sanantonio', 'sas', 'spurs', 'sanantoniospurs'],
            'Toronto': ['toronto', 'raptors', 'tor', 'torontoraptors'],
            'Utah': ['utah', 'jazz', 'uta', 'utahjazz'],
            'Washington': ['washington', 'wizards', 'was', 'washingtonwizards']
        }
